use_frameworks!
platform:ios, '10.0'
target 'FCLib_Example' do
  pod 'FCLib', :path => '../'

  target 'FCLib_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
